import type {
  CashHolding,
  FundHolding,
  FundMarketData,
  FundPeerComparison,
  GoldHolding,
  StockHolding,
  TransactionLog,
} from "@/lib/types";

const navSeries = (start: number, deltas: number[]) =>
  deltas.map((delta, index) => ({
    date: `2026-${String(index + 1).padStart(2, "0")}-28`,
    nav: Number((start + delta).toFixed(4)),
  }));

export const asOfDate = "2026-06-29";

export const fundHoldings: FundHolding[] = [
  {
    code: "160213",
    name: "南方纳斯达克100指数(QDII)A",
    assetType: "fund",
    account: "支付宝",
    theme: "纳指100/QDII",
    fundType: "QDII指数",
    fundCompany: "南方基金",
    fundManager: "罗文杰",
    amount: 12080,
    shares: 6420.55,
    costAmount: 11280,
    costNav: 1.7568,
    buyDate: "2026-02-14",
    lastAddDate: "2026-06-10",
    isQdii: true,
    riskTags: ["QDII_T2", "汇率敏感"],
  },
  {
    code: "007300",
    name: "国联安中证半导体ETF联接A",
    assetType: "fund",
    account: "支付宝",
    theme: "半导体",
    fundType: "ETF联接",
    fundCompany: "国联安基金",
    fundManager: "黄欣",
    amount: 9980,
    shares: 8820,
    costAmount: 10460,
    costNav: 1.1859,
    buyDate: "2026-06-24",
    lastAddDate: "2026-06-24",
    isQdii: false,
    riskTags: ["未满7天", "波动较高", "长期跑输"],
  },
  {
    code: "003095",
    name: "中欧医疗健康混合A",
    assetType: "fund",
    account: "京东",
    theme: "医药",
    fundType: "主动权益",
    fundCompany: "中欧基金",
    fundManager: "葛兰",
    amount: 8730,
    shares: 5920.1,
    costAmount: 9800,
    costNav: 1.6554,
    buyDate: "2025-11-03",
    lastAddDate: "2026-05-20",
    isQdii: false,
    riskTags: ["长期跑输"],
  },
  {
    code: "000307",
    name: "易方达黄金ETF联接C",
    assetType: "fund",
    account: "京东",
    theme: "黄金",
    fundType: "商品基金",
    fundCompany: "易方达基金",
    fundManager: "鲍杰",
    amount: 5120,
    shares: 3180,
    costAmount: 4800,
    costNav: 1.5094,
    buyDate: "2026-04-08",
    lastAddDate: "2026-06-18",
    isQdii: false,
    riskTags: ["仓位偏高"],
  },
  {
    code: "100032",
    name: "富国中证红利指数增强A",
    assetType: "fund",
    account: "支付宝",
    theme: "红利",
    fundType: "指数增强",
    fundCompany: "富国基金",
    fundManager: "方旻",
    amount: 5860,
    shares: 4020,
    costAmount: 5400,
    costNav: 1.3433,
    buyDate: "2026-01-18",
    lastAddDate: "2026-06-03",
    isQdii: false,
    riskTags: ["小仓观察"],
  },
];

export const fundMarketData: FundMarketData[] = [
  {
    fundCode: "160213",
    latestConfirmedNav: 1.848,
    previousConfirmedNav: 1.832,
    confirmedDate: "2026-06-27",
    intradayEstimatedNav: 1.872,
    intradayChangePct: 1.31,
    fundSizeYi: 52.4,
    managementFeePct: 0.8,
    custodyFeePct: 0.25,
    salesServiceFeePct: 0,
    trackingErrorPct: 0.89,
    maxDrawdownPct: -24.8,
    volatilityPct: 21.6,
    sharpeRatio: 0.82,
    managerTenureYears: 5.4,
    subscriptionStatus: "限额申购",
    redemptionStatus: "开放赎回",
    purchaseLimitAmount: 10000,
    indexName: "纳斯达克100",
    indexChangePct: 1.12,
    fxRate: 7.163,
    fxChangePct: 0.18,
    qdiiDelayDays: 2,
    topHoldings: [
      { name: "Microsoft", weightPct: 8.9, sector: "软件" },
      { name: "NVIDIA", weightPct: 7.7, sector: "半导体" },
      { name: "Apple", weightPct: 7.4, sector: "消费电子" },
      { name: "Amazon", weightPct: 5.2, sector: "云与电商" },
      { name: "Broadcom", weightPct: 4.6, sector: "半导体" },
    ],
    performanceSeries: navSeries(1.42, [0.05, 0.12, 0.2, 0.19, 0.31, 0.43]),
  },
  {
    fundCode: "007300",
    latestConfirmedNav: 1.142,
    previousConfirmedNav: 1.154,
    confirmedDate: "2026-06-28",
    intradayEstimatedNav: 1.131,
    intradayChangePct: -0.96,
    fundSizeYi: 8.7,
    managementFeePct: 0.5,
    custodyFeePct: 0.1,
    salesServiceFeePct: 0,
    trackingErrorPct: 1.35,
    maxDrawdownPct: -37.2,
    volatilityPct: 32.4,
    sharpeRatio: 0.24,
    managerTenureYears: 4.8,
    subscriptionStatus: "开放申购",
    redemptionStatus: "开放赎回",
    topHoldings: [
      { name: "中芯国际", weightPct: 7.8, sector: "晶圆代工" },
      { name: "北方华创", weightPct: 6.4, sector: "设备" },
      { name: "韦尔股份", weightPct: 4.9, sector: "设计" },
      { name: "兆易创新", weightPct: 4.6, sector: "存储" },
      { name: "沪硅产业", weightPct: 3.8, sector: "材料" },
    ],
    performanceSeries: navSeries(1.28, [-0.02, -0.06, -0.11, -0.08, -0.13, -0.15]),
  },
  {
    fundCode: "003095",
    latestConfirmedNav: 1.481,
    previousConfirmedNav: 1.488,
    confirmedDate: "2026-06-28",
    intradayEstimatedNav: 1.475,
    intradayChangePct: -0.41,
    fundSizeYi: 113.6,
    managementFeePct: 1.2,
    custodyFeePct: 0.2,
    salesServiceFeePct: 0,
    maxDrawdownPct: -44.6,
    volatilityPct: 28.1,
    sharpeRatio: 0.12,
    managerTenureYears: 8.1,
    subscriptionStatus: "开放申购",
    redemptionStatus: "开放赎回",
    topHoldings: [
      { name: "恒瑞医药", weightPct: 8.8, sector: "创新药" },
      { name: "迈瑞医疗", weightPct: 7.2, sector: "医疗器械" },
      { name: "药明康德", weightPct: 5.1, sector: "CXO" },
      { name: "爱尔眼科", weightPct: 4.2, sector: "医疗服务" },
      { name: "泰格医药", weightPct: 3.6, sector: "临床CRO" },
    ],
    performanceSeries: navSeries(1.69, [-0.04, -0.09, -0.14, -0.18, -0.19, -0.21]),
  },
  {
    fundCode: "000307",
    latestConfirmedNav: 1.611,
    previousConfirmedNav: 1.603,
    confirmedDate: "2026-06-28",
    intradayEstimatedNav: 1.619,
    intradayChangePct: 0.5,
    fundSizeYi: 26.5,
    managementFeePct: 0.15,
    custodyFeePct: 0.05,
    salesServiceFeePct: 0.25,
    trackingErrorPct: 0.31,
    maxDrawdownPct: -12.4,
    volatilityPct: 14.2,
    sharpeRatio: 0.66,
    managerTenureYears: 3.9,
    subscriptionStatus: "开放申购",
    redemptionStatus: "开放赎回",
    topHoldings: [
      { name: "上海金AU9999", weightPct: 88.2, sector: "实物黄金" },
      { name: "银行存款", weightPct: 5.1, sector: "现金管理" },
      { name: "黄金租赁", weightPct: 3.4, sector: "商品策略" },
      { name: "国债逆回购", weightPct: 2.1, sector: "流动性" },
      { name: "其他", weightPct: 1.2, sector: "其他" },
    ],
    performanceSeries: navSeries(1.34, [0.04, 0.09, 0.12, 0.16, 0.21, 0.27]),
  },
  {
    fundCode: "100032",
    latestConfirmedNav: 1.456,
    previousConfirmedNav: 1.451,
    confirmedDate: "2026-06-28",
    intradayEstimatedNav: 1.462,
    intradayChangePct: 0.41,
    fundSizeYi: 38.9,
    managementFeePct: 1,
    custodyFeePct: 0.2,
    salesServiceFeePct: 0,
    trackingErrorPct: 1.08,
    maxDrawdownPct: -18.5,
    volatilityPct: 17.1,
    sharpeRatio: 0.58,
    managerTenureYears: 7.2,
    subscriptionStatus: "开放申购",
    redemptionStatus: "开放赎回",
    topHoldings: [
      { name: "中国神华", weightPct: 4.9, sector: "能源" },
      { name: "长江电力", weightPct: 4.6, sector: "公用事业" },
      { name: "招商银行", weightPct: 3.9, sector: "银行" },
      { name: "中国移动", weightPct: 3.7, sector: "通信" },
      { name: "陕西煤业", weightPct: 3.5, sector: "能源" },
    ],
    performanceSeries: navSeries(1.29, [0.02, 0.06, 0.08, 0.1, 0.14, 0.17]),
  },
];

export const fundPeerComparisons: FundPeerComparison[] = [
  {
    fundCode: "160213",
    fundName: "南方纳斯达克100指数(QDII)A",
    theme: "纳指100/QDII",
    fundSizeYi: 52.4,
    fundType: "QDII指数",
    returns: { week1: 2.4, month1: 4.8, month3: 9.2, month6: 14.1, year1: 18.6, year3: 44.3 },
    maxDrawdownPct: -24.8,
    volatilityPct: 21.6,
    sharpeRatio: 0.82,
    trackingErrorPct: 0.89,
    feePct: 1.05,
    managerTenureYears: 5.4,
    fundCompany: "南方基金",
    purchaseLimitAmount: 10000,
    tradingStatus: "限购",
    suitableForDca: true,
  },
  {
    fundCode: "270042",
    fundName: "广发纳斯达克100ETF联接(QDII)A",
    theme: "纳指100/QDII",
    fundSizeYi: 78.1,
    fundType: "ETF联接",
    returns: { week1: 2.6, month1: 5.1, month3: 10.4, month6: 15.8, year1: 21.2, year3: 48.9 },
    maxDrawdownPct: -23.6,
    volatilityPct: 21.1,
    sharpeRatio: 0.91,
    trackingErrorPct: 0.52,
    feePct: 0.8,
    managerTenureYears: 6.6,
    fundCompany: "广发基金",
    purchaseLimitAmount: 5000,
    tradingStatus: "限购",
    suitableForDca: true,
  },
  {
    fundCode: "040046",
    fundName: "华安纳斯达克100ETF联接(QDII)A",
    theme: "纳指100/QDII",
    fundSizeYi: 31.7,
    fundType: "ETF联接",
    returns: { week1: 2.5, month1: 4.9, month3: 9.8, month6: 15.1, year1: 20.4, year3: 46.7 },
    maxDrawdownPct: -24.1,
    volatilityPct: 21.3,
    sharpeRatio: 0.88,
    trackingErrorPct: 0.61,
    feePct: 0.85,
    managerTenureYears: 4.2,
    fundCompany: "华安基金",
    purchaseLimitAmount: 3000,
    tradingStatus: "正常申赎",
    suitableForDca: true,
  },
  {
    fundCode: "161130",
    fundName: "易方达纳斯达克100指数(QDII)A",
    theme: "纳指100/QDII",
    fundSizeYi: 11.3,
    fundType: "QDII指数",
    returns: { week1: 2.2, month1: 4.4, month3: 8.7, month6: 13.2, year1: 17.1, year3: 39.9 },
    maxDrawdownPct: -26.5,
    volatilityPct: 22.8,
    sharpeRatio: 0.73,
    trackingErrorPct: 1.08,
    feePct: 1.1,
    managerTenureYears: 2.8,
    fundCompany: "易方达基金",
    tradingStatus: "正常申赎",
    suitableForDca: true,
  },
  {
    fundCode: "007300",
    fundName: "国联安中证半导体ETF联接A",
    theme: "半导体",
    fundSizeYi: 8.7,
    fundType: "ETF联接",
    returns: { week1: -1.8, month1: -4.2, month3: -8.3, month6: -12.5, year1: -9.6, year3: -21.8 },
    maxDrawdownPct: -37.2,
    volatilityPct: 32.4,
    sharpeRatio: 0.24,
    trackingErrorPct: 1.35,
    feePct: 0.6,
    managerTenureYears: 4.8,
    fundCompany: "国联安基金",
    tradingStatus: "正常申赎",
    suitableForDca: false,
  },
  {
    fundCode: "012969",
    fundName: "华夏国证半导体芯片ETF联接A",
    theme: "半导体",
    fundSizeYi: 29.4,
    fundType: "ETF联接",
    returns: { week1: -0.8, month1: -1.6, month3: -2.4, month6: 3.2, year1: 7.8, year3: -5.7 },
    maxDrawdownPct: -31.8,
    volatilityPct: 29.2,
    sharpeRatio: 0.42,
    trackingErrorPct: 0.82,
    feePct: 0.45,
    managerTenureYears: 5.1,
    fundCompany: "华夏基金",
    purchaseLimitAmount: 20000,
    tradingStatus: "正常申赎",
    suitableForDca: true,
  },
  {
    fundCode: "008888",
    fundName: "招商中证半导体产业ETF联接A",
    theme: "半导体",
    fundSizeYi: 18.6,
    fundType: "ETF联接",
    returns: { week1: -0.4, month1: -0.9, month3: -1.8, month6: 4.6, year1: 9.1, year3: -3.4 },
    maxDrawdownPct: -30.5,
    volatilityPct: 28.6,
    sharpeRatio: 0.48,
    trackingErrorPct: 0.78,
    feePct: 0.5,
    managerTenureYears: 3.7,
    fundCompany: "招商基金",
    tradingStatus: "正常申赎",
    suitableForDca: true,
  },
  {
    fundCode: "003095",
    fundName: "中欧医疗健康混合A",
    theme: "医药",
    fundSizeYi: 113.6,
    fundType: "主动权益",
    returns: { week1: -0.9, month1: -2.2, month3: -5.6, month6: -9.4, year1: -16.5, year3: -39.4 },
    maxDrawdownPct: -44.6,
    volatilityPct: 28.1,
    sharpeRatio: 0.12,
    feePct: 1.4,
    managerTenureYears: 8.1,
    fundCompany: "中欧基金",
    tradingStatus: "正常申赎",
    suitableForDca: false,
  },
  {
    fundCode: "001915",
    fundName: "宝盈医疗健康沪港深股票A",
    theme: "医药",
    fundSizeYi: 17.5,
    fundType: "主动权益",
    returns: { week1: 0.2, month1: 1.1, month3: 2.8, month6: 6.4, year1: 10.6, year3: -12.1 },
    maxDrawdownPct: -29.3,
    volatilityPct: 23.9,
    sharpeRatio: 0.51,
    feePct: 1.35,
    managerTenureYears: 4.4,
    fundCompany: "宝盈基金",
    purchaseLimitAmount: 50000,
    tradingStatus: "正常申赎",
    suitableForDca: true,
  },
  {
    fundCode: "006002",
    fundName: "工银医药健康股票A",
    theme: "医药",
    fundSizeYi: 42.8,
    fundType: "主动权益",
    returns: { week1: -0.1, month1: 0.7, month3: 2.1, month6: 4.9, year1: 8.2, year3: -10.5 },
    maxDrawdownPct: -31.5,
    volatilityPct: 24.6,
    sharpeRatio: 0.46,
    feePct: 1.35,
    managerTenureYears: 5.9,
    fundCompany: "工银瑞信基金",
    tradingStatus: "正常申赎",
    suitableForDca: true,
  },
  {
    fundCode: "000307",
    fundName: "易方达黄金ETF联接C",
    theme: "黄金",
    fundSizeYi: 26.5,
    fundType: "商品基金",
    returns: { week1: 1.2, month1: 3.4, month3: 6.1, month6: 11.8, year1: 23.4, year3: 45.6 },
    maxDrawdownPct: -12.4,
    volatilityPct: 14.2,
    sharpeRatio: 0.66,
    trackingErrorPct: 0.31,
    feePct: 0.45,
    managerTenureYears: 3.9,
    fundCompany: "易方达基金",
    tradingStatus: "正常申赎",
    suitableForDca: true,
  },
  {
    fundCode: "518880",
    fundName: "华安黄金ETF联接A",
    theme: "黄金",
    fundSizeYi: 64.2,
    fundType: "商品基金",
    returns: { week1: 1.3, month1: 3.6, month3: 6.4, month6: 12.4, year1: 24.9, year3: 47.5 },
    maxDrawdownPct: -11.8,
    volatilityPct: 13.8,
    sharpeRatio: 0.72,
    trackingErrorPct: 0.24,
    feePct: 0.35,
    managerTenureYears: 6.3,
    fundCompany: "华安基金",
    tradingStatus: "正常申赎",
    suitableForDca: true,
  },
  {
    fundCode: "100032",
    fundName: "富国中证红利指数增强A",
    theme: "红利",
    fundSizeYi: 38.9,
    fundType: "指数增强",
    returns: { week1: 0.8, month1: 2.1, month3: 4.2, month6: 7.5, year1: 13.9, year3: 28.6 },
    maxDrawdownPct: -18.5,
    volatilityPct: 17.1,
    sharpeRatio: 0.58,
    trackingErrorPct: 1.08,
    feePct: 1.2,
    managerTenureYears: 7.2,
    fundCompany: "富国基金",
    tradingStatus: "正常申赎",
    suitableForDca: true,
  },
  {
    fundCode: "090010",
    fundName: "大成中证红利指数A",
    theme: "红利",
    fundSizeYi: 22.4,
    fundType: "指数增强",
    returns: { week1: 1.1, month1: 2.7, month3: 5.1, month6: 9.2, year1: 17.4, year3: 34.5 },
    maxDrawdownPct: -16.2,
    volatilityPct: 15.9,
    sharpeRatio: 0.7,
    trackingErrorPct: 0.86,
    feePct: 0.9,
    managerTenureYears: 6.1,
    fundCompany: "大成基金",
    tradingStatus: "正常申赎",
    suitableForDca: true,
  },
];

export const goldHoldings: GoldHolding[] = [
  {
    code: "GOLD-ACC",
    name: "黄金积存金",
    assetType: "gold",
    account: "京东",
    theme: "黄金",
    grams: 45.6,
    costPricePerGram: 512.8,
    currentPricePerGram: 558.6,
    previousPricePerGram: 553.4,
    buyDate: "2025-12-12",
    lastAddDate: "2026-06-12",
    riskTags: ["仓位偏高"],
  },
];

export const stockHoldings: StockHolding[] = [
  {
    code: "NVDA",
    name: "英伟达",
    assetType: "stock",
    account: "京东",
    market: "美股",
    industry: "AI芯片",
    quantity: 8,
    costPrice: 131.2,
    currentPrice: 156.7,
    previousClose: 151.6,
    currency: "USD",
    fxRateToCny: 7.163,
    buyDate: "2026-06-15",
    lastAddDate: "2026-06-15",
    riskTags: ["波动较高", "小仓观察"],
  },
  {
    code: "0700.HK",
    name: "腾讯控股",
    assetType: "stock",
    account: "支付宝",
    market: "港股",
    industry: "互联网平台",
    quantity: 20,
    costPrice: 372,
    currentPrice: 389.8,
    previousClose: 395.4,
    currency: "HKD",
    fxRateToCny: 0.914,
    buyDate: "2026-03-22",
    lastAddDate: "2026-06-05",
    riskTags: ["小仓观察"],
  },
];

export const cashHolding: CashHolding = {
  code: "CASH-CNY",
  name: "现金余额",
  assetType: "cash",
  account: "支付宝",
  amount: 8200,
};

export const qdiiMarketSnapshot = {
  updatedAt: "2026-06-29 09:35",
  usdCny: 7.163,
  usdCnyChangePct: 0.18,
  indices: [
    { name: "纳斯达克100", changePct: 1.12, estimatedNavImpactPct: 1.3 },
    { name: "标普500", changePct: 0.74, estimatedNavImpactPct: 0.92 },
    { name: "道琼斯", changePct: 0.38, estimatedNavImpactPct: 0.56 },
  ],
  note: "QDII净值通常存在T+1至T+2确认延迟，页面展示为估算值。",
};

export const transactionLogs: TransactionLog[] = [
  {
    id: "txn-001",
    date: "2026-06-24",
    account: "支付宝",
    assetType: "fund",
    code: "007300",
    name: "国联安中证半导体ETF联接A",
    action: "加仓",
    amount: 2800,
    shares: 2361.08,
    price: 1.1859,
    confirmedProfit: -12.4,
    estimatedProfit: -26.9,
    fee: 2.8,
    note: "补仓后未满7天，赎回需特别提醒。",
  },
  {
    id: "txn-002",
    date: "2026-06-15",
    account: "京东",
    assetType: "stock",
    code: "NVDA",
    name: "英伟达",
    action: "买入",
    amount: 7515.4,
    shares: 8,
    price: 131.2,
    confirmedProfit: 0,
    estimatedProfit: 292.25,
    fee: 12,
    note: "小仓跟踪AI主线。",
  },
  {
    id: "txn-003",
    date: "2026-05-01",
    account: "支付宝",
    assetType: "cash",
    code: "CASH-CNY",
    name: "现金余额",
    action: "现金转入",
    amount: 5000,
    note: "备用现金。",
  },
  {
    id: "txn-004",
    date: "2026-06-28",
    account: "京东",
    assetType: "fund",
    code: "003095",
    name: "中欧医疗健康混合A",
    action: "修改收益",
    amount: 0,
    confirmedProfit: -68.2,
    estimatedProfit: -76.96,
    note: "晚间确认净值后修正当日收益。",
  },
  {
    id: "txn-005",
    date: "2026-06-29",
    account: "支付宝",
    assetType: "fund",
    code: "160213",
    name: "南方纳斯达克100指数(QDII)A",
    action: "修改净值",
    amount: 0,
    price: 1.872,
    confirmedProfit: 102.73,
    estimatedProfit: 257.22,
    note: "QDII估算净值，等待基金公司确认。",
  },
];
